### ISSUE TITLE
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'paragraphStyle'; did you mean 'paragraphRange'?

### ISSUE THREAD

**Issue by carlosbernabeujuan** [vpeschenkov/LetterAvatarKit#10]
I get this error when building, I have the latest version of Cocoapods, Swift and xCode

**Comment by vpeschenkov** [comment]
Hello @carlosbernabeujuan,

Which version of Swift do you use? The error seems to be possible only if you use Swift < 4.0. But I had removed support of Swift < 4.0 in the latest release, probably this is a reason why you got that error. Should we keep supporting Swift < 4.0?

Thank you!

**Comment by carlosbernabeujuan** [comment]
Hi Victor, my bad completely, sorry for the inconvenience, you can delete the issue.
