### ISSUE TITLE
Crash: Fatal error: cannot increment beyond endIndex

### ISSUE THREAD

**Issue by pappalar** [vpeschenkov/LetterAvatarKit#11]
https://github.com/vpeschenkov/LetterAvatarKit/blob/0ce7d0c41420516775a07e354a1ac9512208fd35/LetterAvatarKit/LetterAvatarBuilder.swift#L105

If single Letter is passed as false but the string is a single char, this line fails due to out of bounds exception.

I think it would be safer to avoid this crash inside the framework by checking the size of the string before subscripting.

If the string is only 1 letter lenght, then the `singleLetter` configuration could be ignored

**Comment by vpeschenkov** [comment]
Hello @racer1988,

You are right we have to check a length of a string before getting the second character. I'll fix this over the week.

Thank you for reporting!

**Comment by vpeschenkov** [comment]
@racer1988 done. Let me know if you find something else to fix here 🙂

**Comment by pappalar** [comment]
Awesome! Thanks
