### ISSUE TITLE
Compilation issue Xcode 8 - swift 3.0

### ISSUE THREAD

**Issue by ijameelkhan** [vpeschenkov/LetterAvatarKit#4]
HI , 

I am getting compilation issue on this line.

```swift
if let letter = firstComponent.first  
```

the issue says
"'String' has no member 'first'"

can you add this extension to make it work ? on swift 3.0 as well.

```swift
extension String{
    
    
    func first()->String{
        
        
        return String(self.characters.prefix(1))
        
    }    
}

```

**Comment by vpeschenkov** [comment]
@ijameelkhan Hi. Thank you for your time. This framework supports only Swift 3.2 and later. I've added your category. Will be great if you check how it works on Swift 3.0. Because, I don't have oportunity to do that.

**Comment by ijameelkhan** [comment]
This worked nicely. Thank you.
