### ISSUE TITLE
Draw circle image

### ISSUE THREAD

**Issue by nawrasg** [vpeschenkov/LetterAvatarKit#6]
Hi,

First of all, thank you very much for this library. Great job :)
I was wondering how I can draw a circular image instead of a rectangular one?

Nawras

**Comment by vpeschenkov** [comment]
Hello, thanks for the question! It's not possible to generate a circular image by `LetterAvatarKit`. However, you can use [`cornerRadius`](https://developer.apple.com/documentation/quartzcore/calayer/1410818-cornerradius) and get the same result but using [`UIImageView`](https://developer.apple.com/documentation/uikit/uiimageview). Please, see the example below:

```
avatarImageView?.layer.cornerRadius = max(avatarImageView!.bounds.size.width / 2.0, avatarImageView!.bounds.size.height / 2.0)
avatarImageView?.layer.masksToBounds = true
``` 

Also, you can use [`UIBezierPath`](https://developer.apple.com/documentation/uikit/uibezierpath) to get any `UIImageView` shape.

**Comment by nawrasg** [comment]
Awesome :) Thank you very much !
Nawras
