### ISSUE TITLE
multiple Avatars in one UIImage

### ISSUE THREAD

**Issue by ijameelkhan** [vpeschenkov/LetterAvatarKit#7]
Can we add feature where where it can create UIImage for a group of Avatars something like iMessages. 

<img width="86" alt="screen shot 2018-01-09 at 4 21 05 am" src="https://user-images.githubusercontent.com/1882875/34697377-a6f8327e-f4f4-11e7-954c-8684482b2b95.png">

**Comment by vpeschenkov** [comment]
@ijameelkhan Hello! Thank you! I'm sorry for keeping you waiting. I’ve thought about your suggestion. It's good, however, I don't think that it will be good for LetterAvatarKit. Here are the reasons why:
- It looks more like a control, not just an image
- It looks more like an independent framework with special requirements than a feature to LetterAvatarKit
- It has a strong dependence on requirement, and can’t be built as a universal solution
- It has more than one implementation at least, and it will be complicated to make a universal solution

Finally, It's still possible to make a group of avatars using LetterAvatarKit. Yes, It requires some additional work, but it allows to make any solution by requirements. For the reasons stated above I won’t include this feature into LetterAvatarKit :-(

If you have any questions, please feel free to ask me!
