### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by connorcowling** [vpeschenkov/LetterAvatarKit#9]
In the Readme, you show the letter avatars as square or rounded but I am having difficulty doing this. Can you share the code for this please?

**Comment by vpeschenkov** [comment]
Hi, thanks for the question! You can use the [cornerRadius](https://developer.apple.com/documentation/quartzcore/calayer/1410818-cornerradius) property of [CALayer](https://developer.apple.com/documentation/quartzcore/calayer) and get a rounded view. There is the example of code to get a rounded view:
```
avatarImageView.layer.cornerRadius = max(avatarImageView.bounds.size.width / 2.0, avatarImageView.bounds.size.height / 2.0)
avatarImageView.layer.masksToBounds = true
```

Also, you can use [UIBezierPath](https://developer.apple.com/documentation/uikit/uibezierpath) to get any UIImageView shape.

**Comment by connorcowling** [comment]
<img width="976" alt="screen shot 2018-05-09 at 15 48 53" src="https://user-images.githubusercontent.com/29253717/39818156-87e92342-53a0-11e8-8fe0-0a156c88ef2b.png">

**Comment by vpeschenkov** [comment]
I've used the given code with a few changes in auto layouts. The great article for reading https://www.appcoda.com/ios-programming-circular-image-calayer/. However, you should be able to adapt this code to your project.

![](https://i.imgur.com/vjfquoI.png)

**Comment by connorcowling** [comment]
Thanks, it was the constraints that were the issue :)
Also, `configuration.lettersFont = UIFont.systemFont(ofSize: 12.0)` does not change the size of the letters. 
<img width="471" alt="screen shot 2018-05-09 at 16 38 21" src="https://user-images.githubusercontent.com/29253717/39820977-6a173ece-53a7-11e8-969d-76022589e10a.png">

**Comment by vpeschenkov** [comment]
Yes, it is. The font size is calculated in this line: ```lettersFont.withSize(min(size.height, size.width) / 2.0)```. That property just allows to set the type of font, like this: ```UIFont.systemFont(ofSize: 16.0, weight: .light)```.

In your case, you have drawn the image bigger than the view, and it is possible to fix that by adding the next line of code: ```avatarImageView?.contentMode = .scaleAspectFill```. But it would be better to change the size value in the configuration object: ```configuration.size = CGSize(width: *width of the view*, height: *height of the view*)```. We should know the size of the view before drawing.  

| .regular | .light                        |
| -------- | -------- |
| ![](https://i.imgur.com/Gr7gClH.png) | ![](https://i.imgur.com/6sa7tUe.png) |

**Comment by vpeschenkov** [comment]
```
let configuration = LetterAvatarBuilderConfiguration()
configuration.size = CGSize(width: UIScreen.main.bounds.size.width, height: UIScreen.main.bounds.size.width)
configuration.username = "Letter Avatar"
avatarImageView?.image = UIImage.makeLetterAvatar(withConfiguration: configuration)
avatarImageView?.contentMode = .scaleAspectFill
```
![](https://i.imgur.com/gsYjd9M.png)

**Comment by connorcowling** [comment]
Thanks for the support 👍

**Comment by vpeschenkov** [comment]
You're welcome 😄
